//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.586.
// 
#pragma warning disable 1591

namespace BettaBasketBatch.com.qcmoultonordervision {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ORDAPISoap", Namespace="https://www.moultonordervision.com/Ws/ORDAPI.asmx")]
    public partial class ORDAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OrderNewAPIOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderNewAPITrackableOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderAPIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ORDAPI() {
            this.Url = global::BettaBasketBatch.Properties.Settings.Default.AhhBraBatch_com_qcmoultonordervision_ORDAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OrderNewAPICompletedEventHandler OrderNewAPICompleted;
        
        /// <remarks/>
        public event OrderNewAPITrackableCompletedEventHandler OrderNewAPITrackableCompleted;
        
        /// <remarks/>
        public event OrderAPICompletedEventHandler OrderAPICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.moultonordervision.com/Ws/ORDAPI.asmx/OrderNewAPI", RequestNamespace="https://www.moultonordervision.com/Ws/ORDAPI.asmx", ResponseNamespace="https://www.moultonordervision.com/Ws/ORDAPI.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode OrderNewAPI(string UserName, string Password, string GroupCode, string ClNo, string Project, string XMLFormatCode, string OrdXML) {
            object[] results = this.Invoke("OrderNewAPI", new object[] {
                        UserName,
                        Password,
                        GroupCode,
                        ClNo,
                        Project,
                        XMLFormatCode,
                        OrdXML});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void OrderNewAPIAsync(string UserName, string Password, string GroupCode, string ClNo, string Project, string XMLFormatCode, string OrdXML) {
            this.OrderNewAPIAsync(UserName, Password, GroupCode, ClNo, Project, XMLFormatCode, OrdXML, null);
        }
        
        /// <remarks/>
        public void OrderNewAPIAsync(string UserName, string Password, string GroupCode, string ClNo, string Project, string XMLFormatCode, string OrdXML, object userState) {
            if ((this.OrderNewAPIOperationCompleted == null)) {
                this.OrderNewAPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderNewAPIOperationCompleted);
            }
            this.InvokeAsync("OrderNewAPI", new object[] {
                        UserName,
                        Password,
                        GroupCode,
                        ClNo,
                        Project,
                        XMLFormatCode,
                        OrdXML}, this.OrderNewAPIOperationCompleted, userState);
        }
        
        private void OnOrderNewAPIOperationCompleted(object arg) {
            if ((this.OrderNewAPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderNewAPICompleted(this, new OrderNewAPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.moultonordervision.com/Ws/ORDAPI.asmx/OrderNewAPITrackable", RequestNamespace="https://www.moultonordervision.com/Ws/ORDAPI.asmx", ResponseNamespace="https://www.moultonordervision.com/Ws/ORDAPI.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode OrderNewAPITrackable(string UserName, string Password, string GroupCode, string UniqueId, string ClNo, string Project, string XMLFormatCode, string OrdXML) {
            object[] results = this.Invoke("OrderNewAPITrackable", new object[] {
                        UserName,
                        Password,
                        GroupCode,
                        UniqueId,
                        ClNo,
                        Project,
                        XMLFormatCode,
                        OrdXML});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void OrderNewAPITrackableAsync(string UserName, string Password, string GroupCode, string UniqueId, string ClNo, string Project, string XMLFormatCode, string OrdXML) {
            this.OrderNewAPITrackableAsync(UserName, Password, GroupCode, UniqueId, ClNo, Project, XMLFormatCode, OrdXML, null);
        }
        
        /// <remarks/>
        public void OrderNewAPITrackableAsync(string UserName, string Password, string GroupCode, string UniqueId, string ClNo, string Project, string XMLFormatCode, string OrdXML, object userState) {
            if ((this.OrderNewAPITrackableOperationCompleted == null)) {
                this.OrderNewAPITrackableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderNewAPITrackableOperationCompleted);
            }
            this.InvokeAsync("OrderNewAPITrackable", new object[] {
                        UserName,
                        Password,
                        GroupCode,
                        UniqueId,
                        ClNo,
                        Project,
                        XMLFormatCode,
                        OrdXML}, this.OrderNewAPITrackableOperationCompleted, userState);
        }
        
        private void OnOrderNewAPITrackableOperationCompleted(object arg) {
            if ((this.OrderNewAPITrackableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderNewAPITrackableCompleted(this, new OrderNewAPITrackableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.moultonordervision.com/Ws/ORDAPI.asmx/OrderAPI", RequestNamespace="https://www.moultonordervision.com/Ws/ORDAPI.asmx", ResponseNamespace="https://www.moultonordervision.com/Ws/ORDAPI.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode OrderAPI(string RequestXML) {
            object[] results = this.Invoke("OrderAPI", new object[] {
                        RequestXML});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void OrderAPIAsync(string RequestXML) {
            this.OrderAPIAsync(RequestXML, null);
        }
        
        /// <remarks/>
        public void OrderAPIAsync(string RequestXML, object userState) {
            if ((this.OrderAPIOperationCompleted == null)) {
                this.OrderAPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderAPIOperationCompleted);
            }
            this.InvokeAsync("OrderAPI", new object[] {
                        RequestXML}, this.OrderAPIOperationCompleted, userState);
        }
        
        private void OnOrderAPIOperationCompleted(object arg) {
            if ((this.OrderAPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderAPICompleted(this, new OrderAPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void OrderNewAPICompletedEventHandler(object sender, OrderNewAPICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderNewAPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderNewAPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void OrderNewAPITrackableCompletedEventHandler(object sender, OrderNewAPITrackableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderNewAPITrackableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderNewAPITrackableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void OrderAPICompletedEventHandler(object sender, OrderAPICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderAPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderAPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591