//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace AhhBraBatch.Application_Code.BusinessObjects
{
}

namespace AhhBraBatch
{
}
namespace AhhBraBatch.Application_Code.BusinessObjects
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Order
    {

        private string callCenterField;

        private OrderOrderHeader[] orderHeaderField;

        private OrderOrderDetailLineItem[] orderDetailField;

        private OrderGiftMessage[] giftMessageField;

        private OrderFinancial[] financialField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallCenter
        {
            get
            {
                return this.callCenterField;
            }
            set
            {
                this.callCenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderHeader", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OrderOrderHeader[] OrderHeader
        {
            get
            {
                return this.orderHeaderField;
            }
            set
            {
                this.orderHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LineItem", typeof(OrderOrderDetailLineItem), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public OrderOrderDetailLineItem[] OrderDetail
        {
            get
            {
                return this.orderDetailField;
            }
            set
            {
                this.orderDetailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GiftMessage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OrderGiftMessage[] GiftMessage
        {
            get
            {
                return this.giftMessageField;
            }
            set
            {
                this.giftMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Financial", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OrderFinancial[] Financial
        {
            get
            {
                return this.financialField;
            }
            set
            {
                this.financialField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OrderOrderHeader
    {

        private string gROUP_CODEField;

        private string cASH_BATField;

        private string sEQUENCE_NUMBERField;

        private string uSERField;

        private string dATE_ORDField;

        private string cL_NOField;

        private string cSOURCEField;

        private string cMEDIAField;

        private string cREDCDField;

        private string eXPDTField;

        private string pROJECTField;

        private string cARRIERField;

        private string sVC_TYPEField;

        private string aMTPAYField;

        private string cHECK_NOField;

        private string bANKNOField;

        private string mICRCODEField;

        private string pAY_TYPEField;

        private string nUM_PYMNTSField;

        private string eMAILField;

        private string cOMPANYField;

        private string f_NAMEField;

        private string l_NAMEField;

        private string aDDR_1Field;

        private string aDDR_2Field;

        private string cITYField;

        private string stField;

        private string zIPField;

        private string pHONEField;

        private string pHONE_EXTField;

        private string cOUNTRY_CODEField;

        private string oPT_INField;

        private string oPT_OUTField;

        private string aDJ_CODEField;

        private string aMT_DISCField;

        private string mISCField;

        private string sALE_AMOUNTField;

        private string sHIPPING_HANDLING_AMOUNTField;

        private string tAX_AMOUNTField;

        private string tOTAL_CHARGE_AMOUNTField;

        private string cREDIT_CARD_DISCOUNT_AMOUNTField;

        private string iTEM_DISCOUNT_PERCENTField;

        private string cREDIT_CARD_DISCOUNT_PERCENTField;

        private string pURCHASE_ORDERField;

        private string sERIES_INTERVALField;

        private string sRC_CDField;

        private string cVV2Field;

        private string bILL_TO_COMPANYField;

        private string bILL_TO_L_NAMEField;

        private string bILL_TO_F_NAMEField;

        private string bILL_TO_ADDR_1Field;

        private string bILL_TO_ADDR_2Field;

        private string bILL_TO_CITYField;

        private string bILL_TO_STField;

        private string bILL_TO_ZIPField;

        private string bILL_TO_COUNTRY_CODEField;

        private string uNIQUEIDField;

        private string hAS_FINANCIALField;

        private string hAS_GIFT_RECField;

        private string hAS_CALLCENTER_RECField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GROUP_CODE
        {
            get
            {
                return this.gROUP_CODEField;
            }
            set
            {
                this.gROUP_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CASH_BAT
        {
            get
            {
                return this.cASH_BATField;
            }
            set
            {
                this.cASH_BATField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEQUENCE_NUMBER
        {
            get
            {
                return this.sEQUENCE_NUMBERField;
            }
            set
            {
                this.sEQUENCE_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USER
        {
            get
            {
                return this.uSERField;
            }
            set
            {
                this.uSERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DATE_ORD
        {
            get
            {
                return this.dATE_ORDField;
            }
            set
            {
                this.dATE_ORDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CL_NO
        {
            get
            {
                return this.cL_NOField;
            }
            set
            {
                this.cL_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CSOURCE
        {
            get
            {
                return this.cSOURCEField;
            }
            set
            {
                this.cSOURCEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CMEDIA
        {
            get
            {
                return this.cMEDIAField;
            }
            set
            {
                this.cMEDIAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREDCD
        {
            get
            {
                return this.cREDCDField;
            }
            set
            {
                this.cREDCDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EXPDT
        {
            get
            {
                return this.eXPDTField;
            }
            set
            {
                this.eXPDTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PROJECT
        {
            get
            {
                return this.pROJECTField;
            }
            set
            {
                this.pROJECTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CARRIER
        {
            get
            {
                return this.cARRIERField;
            }
            set
            {
                this.cARRIERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SVC_TYPE
        {
            get
            {
                return this.sVC_TYPEField;
            }
            set
            {
                this.sVC_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AMTPAY
        {
            get
            {
                return this.aMTPAYField;
            }
            set
            {
                this.aMTPAYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHECK_NO
        {
            get
            {
                return this.cHECK_NOField;
            }
            set
            {
                this.cHECK_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BANK-NO", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANKNO
        {
            get
            {
                return this.bANKNOField;
            }
            set
            {
                this.bANKNOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MICRCODE
        {
            get
            {
                return this.mICRCODEField;
            }
            set
            {
                this.mICRCODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PAY_TYPE
        {
            get
            {
                return this.pAY_TYPEField;
            }
            set
            {
                this.pAY_TYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUM_PYMNTS
        {
            get
            {
                return this.nUM_PYMNTSField;
            }
            set
            {
                this.nUM_PYMNTSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMPANY
        {
            get
            {
                return this.cOMPANYField;
            }
            set
            {
                this.cOMPANYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F_NAME
        {
            get
            {
                return this.f_NAMEField;
            }
            set
            {
                this.f_NAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string L_NAME
        {
            get
            {
                return this.l_NAMEField;
            }
            set
            {
                this.l_NAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDR_1
        {
            get
            {
                return this.aDDR_1Field;
            }
            set
            {
                this.aDDR_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDR_2
        {
            get
            {
                return this.aDDR_2Field;
            }
            set
            {
                this.aDDR_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CITY
        {
            get
            {
                return this.cITYField;
            }
            set
            {
                this.cITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ST
        {
            get
            {
                return this.stField;
            }
            set
            {
                this.stField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZIP
        {
            get
            {
                return this.zIPField;
            }
            set
            {
                this.zIPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHONE
        {
            get
            {
                return this.pHONEField;
            }
            set
            {
                this.pHONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHONE_EXT
        {
            get
            {
                return this.pHONE_EXTField;
            }
            set
            {
                this.pHONE_EXTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUNTRY_CODE
        {
            get
            {
                return this.cOUNTRY_CODEField;
            }
            set
            {
                this.cOUNTRY_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPT_IN
        {
            get
            {
                return this.oPT_INField;
            }
            set
            {
                this.oPT_INField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OPT_OUT
        {
            get
            {
                return this.oPT_OUTField;
            }
            set
            {
                this.oPT_OUTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADJ_CODE
        {
            get
            {
                return this.aDJ_CODEField;
            }
            set
            {
                this.aDJ_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AMT_DISC
        {
            get
            {
                return this.aMT_DISCField;
            }
            set
            {
                this.aMT_DISCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MISC
        {
            get
            {
                return this.mISCField;
            }
            set
            {
                this.mISCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SALE_AMOUNT
        {
            get
            {
                return this.sALE_AMOUNTField;
            }
            set
            {
                this.sALE_AMOUNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHIPPING_HANDLING_AMOUNT
        {
            get
            {
                return this.sHIPPING_HANDLING_AMOUNTField;
            }
            set
            {
                this.sHIPPING_HANDLING_AMOUNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAX_AMOUNT
        {
            get
            {
                return this.tAX_AMOUNTField;
            }
            set
            {
                this.tAX_AMOUNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTAL_CHARGE_AMOUNT
        {
            get
            {
                return this.tOTAL_CHARGE_AMOUNTField;
            }
            set
            {
                this.tOTAL_CHARGE_AMOUNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREDIT_CARD_DISCOUNT_AMOUNT
        {
            get
            {
                return this.cREDIT_CARD_DISCOUNT_AMOUNTField;
            }
            set
            {
                this.cREDIT_CARD_DISCOUNT_AMOUNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITEM_DISCOUNT_PERCENT
        {
            get
            {
                return this.iTEM_DISCOUNT_PERCENTField;
            }
            set
            {
                this.iTEM_DISCOUNT_PERCENTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CREDIT_CARD_DISCOUNT_PERCENT
        {
            get
            {
                return this.cREDIT_CARD_DISCOUNT_PERCENTField;
            }
            set
            {
                this.cREDIT_CARD_DISCOUNT_PERCENTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PURCHASE_ORDER
        {
            get
            {
                return this.pURCHASE_ORDERField;
            }
            set
            {
                this.pURCHASE_ORDERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERIES_INTERVAL
        {
            get
            {
                return this.sERIES_INTERVALField;
            }
            set
            {
                this.sERIES_INTERVALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SRC_CD
        {
            get
            {
                return this.sRC_CDField;
            }
            set
            {
                this.sRC_CDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CVV2
        {
            get
            {
                return this.cVV2Field;
            }
            set
            {
                this.cVV2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_COMPANY
        {
            get
            {
                return this.bILL_TO_COMPANYField;
            }
            set
            {
                this.bILL_TO_COMPANYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_L_NAME
        {
            get
            {
                return this.bILL_TO_L_NAMEField;
            }
            set
            {
                this.bILL_TO_L_NAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_F_NAME
        {
            get
            {
                return this.bILL_TO_F_NAMEField;
            }
            set
            {
                this.bILL_TO_F_NAMEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_ADDR_1
        {
            get
            {
                return this.bILL_TO_ADDR_1Field;
            }
            set
            {
                this.bILL_TO_ADDR_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_ADDR_2
        {
            get
            {
                return this.bILL_TO_ADDR_2Field;
            }
            set
            {
                this.bILL_TO_ADDR_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_CITY
        {
            get
            {
                return this.bILL_TO_CITYField;
            }
            set
            {
                this.bILL_TO_CITYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_ST
        {
            get
            {
                return this.bILL_TO_STField;
            }
            set
            {
                this.bILL_TO_STField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_ZIP
        {
            get
            {
                return this.bILL_TO_ZIPField;
            }
            set
            {
                this.bILL_TO_ZIPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BILL_TO_COUNTRY_CODE
        {
            get
            {
                return this.bILL_TO_COUNTRY_CODEField;
            }
            set
            {
                this.bILL_TO_COUNTRY_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UNIQUE-ID", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIQUEID
        {
            get
            {
                return this.uNIQUEIDField;
            }
            set
            {
                this.uNIQUEIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HAS_FINANCIAL
        {
            get
            {
                return this.hAS_FINANCIALField;
            }
            set
            {
                this.hAS_FINANCIALField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HAS_GIFT_REC
        {
            get
            {
                return this.hAS_GIFT_RECField;
            }
            set
            {
                this.hAS_GIFT_RECField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HAS_CALLCENTER_REC
        {
            get
            {
                return this.hAS_CALLCENTER_RECField;
            }
            set
            {
                this.hAS_CALLCENTER_RECField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OrderOrderDetailLineItem
    {

        private string qUANTITY_ORDEREDField;

        private string oFFER_CODEField;

        private string oFFER_DESCRIPTIONField;

        private string sELL_SIGNField;

        private string uNIT_PRICEField;

        private string hANDL_SIGNField;

        private string uNIT_SHIPPING_HANDLING_AMOUNTField;

        private string cLIENT_SKUField;

        private string tAXABLE_FLAGField;

        private string cONTINUITY_FLAGField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUANTITY_ORDERED
        {
            get
            {
                return this.qUANTITY_ORDEREDField;
            }
            set
            {
                this.qUANTITY_ORDEREDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OFFER_CODE
        {
            get
            {
                return this.oFFER_CODEField;
            }
            set
            {
                this.oFFER_CODEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OFFER_DESCRIPTION
        {
            get
            {
                return this.oFFER_DESCRIPTIONField;
            }
            set
            {
                this.oFFER_DESCRIPTIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SELL_SIGN
        {
            get
            {
                return this.sELL_SIGNField;
            }
            set
            {
                this.sELL_SIGNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT_PRICE
        {
            get
            {
                return this.uNIT_PRICEField;
            }
            set
            {
                this.uNIT_PRICEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HANDL_SIGN
        {
            get
            {
                return this.hANDL_SIGNField;
            }
            set
            {
                this.hANDL_SIGNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT_SHIPPING_HANDLING_AMOUNT
        {
            get
            {
                return this.uNIT_SHIPPING_HANDLING_AMOUNTField;
            }
            set
            {
                this.uNIT_SHIPPING_HANDLING_AMOUNTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CLIENT_SKU
        {
            get
            {
                return this.cLIENT_SKUField;
            }
            set
            {
                this.cLIENT_SKUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXABLE_FLAG
        {
            get
            {
                return this.tAXABLE_FLAGField;
            }
            set
            {
                this.tAXABLE_FLAGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTINUITY_FLAG
        {
            get
            {
                return this.cONTINUITY_FLAGField;
            }
            set
            {
                this.cONTINUITY_FLAGField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OrderGiftMessage
    {

        private string mESSAGE1Field;

        private string mESSAGE2Field;

        private string mESSAGE3Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE1
        {
            get
            {
                return this.mESSAGE1Field;
            }
            set
            {
                this.mESSAGE1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE2
        {
            get
            {
                return this.mESSAGE2Field;
            }
            set
            {
                this.mESSAGE2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE3
        {
            get
            {
                return this.mESSAGE3Field;
            }
            set
            {
                this.mESSAGE3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OrderFinancial
    {

        private string aUTHORIZATION_SOURCE_IDField;

        private string cVV2_IDField;

        private string aLTERNATE_ACCOUNT_NUMBERField;

        private string tRANSACTION_IDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AUTHORIZATION_SOURCE_ID
        {
            get
            {
                return this.aUTHORIZATION_SOURCE_IDField;
            }
            set
            {
                this.aUTHORIZATION_SOURCE_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CVV2_ID
        {
            get
            {
                return this.cVV2_IDField;
            }
            set
            {
                this.cVV2_IDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ALTERNATE_ACCOUNT_NUMBER
        {
            get
            {
                return this.aLTERNATE_ACCOUNT_NUMBERField;
            }
            set
            {
                this.aLTERNATE_ACCOUNT_NUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TRANSACTION_ID
        {
            get
            {
                return this.tRANSACTION_IDField;
            }
            set
            {
                this.tRANSACTION_IDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private Order[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Order")]
        public Order[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}