//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.586.
// 
#pragma warning disable 1591

namespace BettaBasketBatch.com.shoptvcanada.ws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OMSOrderTakerSoap", Namespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx")]
    public partial class OMSOrderTaker : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConnectionTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePurchaseOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSalesOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateOrderDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOrderConfirmationOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViewOrderDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailViaWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportOrdersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OMSOrderTaker() {
            this.Url = global::BettaBasketBatch.Properties.Settings.Default.AhhBraBatch_com_shoptvcanada_ws_OMSOrderTaker;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConnectionTestCompletedEventHandler ConnectionTestCompleted;
        
        /// <remarks/>
        public event CreatePurchaseOrderCompletedEventHandler CreatePurchaseOrderCompleted;
        
        /// <remarks/>
        public event CreateSalesOrderCompletedEventHandler CreateSalesOrderCompleted;
        
        /// <remarks/>
        public event ValidateOrderDetailsCompletedEventHandler ValidateOrderDetailsCompleted;
        
        /// <remarks/>
        public event SendOrderConfirmationCompletedEventHandler SendOrderConfirmationCompleted;
        
        /// <remarks/>
        public event ViewOrderDetailsCompletedEventHandler ViewOrderDetailsCompleted;
        
        /// <remarks/>
        public event SendEmailViaWSCompletedEventHandler SendEmailViaWSCompleted;
        
        /// <remarks/>
        public event ExportOrdersCompletedEventHandler ExportOrdersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx/ConnectionTest", RequestNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", ResponseNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConnectionTest(bool @bool) {
            object[] results = this.Invoke("ConnectionTest", new object[] {
                        @bool});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConnectionTestAsync(bool @bool) {
            this.ConnectionTestAsync(@bool, null);
        }
        
        /// <remarks/>
        public void ConnectionTestAsync(bool @bool, object userState) {
            if ((this.ConnectionTestOperationCompleted == null)) {
                this.ConnectionTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectionTestOperationCompleted);
            }
            this.InvokeAsync("ConnectionTest", new object[] {
                        @bool}, this.ConnectionTestOperationCompleted, userState);
        }
        
        private void OnConnectionTestOperationCompleted(object arg) {
            if ((this.ConnectionTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConnectionTestCompleted(this, new ConnectionTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx/CreatePurchaseOrder", RequestNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", ResponseNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreatePurchaseOrder(PurchaseOrder order) {
            object[] results = this.Invoke("CreatePurchaseOrder", new object[] {
                        order});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePurchaseOrderAsync(PurchaseOrder order) {
            this.CreatePurchaseOrderAsync(order, null);
        }
        
        /// <remarks/>
        public void CreatePurchaseOrderAsync(PurchaseOrder order, object userState) {
            if ((this.CreatePurchaseOrderOperationCompleted == null)) {
                this.CreatePurchaseOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePurchaseOrderOperationCompleted);
            }
            this.InvokeAsync("CreatePurchaseOrder", new object[] {
                        order}, this.CreatePurchaseOrderOperationCompleted, userState);
        }
        
        private void OnCreatePurchaseOrderOperationCompleted(object arg) {
            if ((this.CreatePurchaseOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePurchaseOrderCompleted(this, new CreatePurchaseOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx/CreateSalesOrder", RequestNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", ResponseNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateSalesOrder(SalesOrder order, bool LiveMode) {
            object[] results = this.Invoke("CreateSalesOrder", new object[] {
                        order,
                        LiveMode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSalesOrderAsync(SalesOrder order, bool LiveMode) {
            this.CreateSalesOrderAsync(order, LiveMode, null);
        }
        
        /// <remarks/>
        public void CreateSalesOrderAsync(SalesOrder order, bool LiveMode, object userState) {
            if ((this.CreateSalesOrderOperationCompleted == null)) {
                this.CreateSalesOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSalesOrderOperationCompleted);
            }
            this.InvokeAsync("CreateSalesOrder", new object[] {
                        order,
                        LiveMode}, this.CreateSalesOrderOperationCompleted, userState);
        }
        
        private void OnCreateSalesOrderOperationCompleted(object arg) {
            if ((this.CreateSalesOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSalesOrderCompleted(this, new CreateSalesOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx/ValidateOrderDetails", RequestNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", ResponseNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateOrderDetails(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, int lngOMSOrderID, int lngOrdersDetailsID, int lngCustomerID, string strOrderType, string strCurrency, string envMode, ref string strSKU) {
            object[] results = this.Invoke("ValidateOrderDetails", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        lngOMSOrderID,
                        lngOrdersDetailsID,
                        lngCustomerID,
                        strOrderType,
                        strCurrency,
                        envMode,
                        strSKU});
            strSKU = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateOrderDetailsAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, int lngOMSOrderID, int lngOrdersDetailsID, int lngCustomerID, string strOrderType, string strCurrency, string envMode, string strSKU) {
            this.ValidateOrderDetailsAsync(strB2BCustomerName, strB2BCustomerEmail, strB2BCustomerPassword, lngOMSOrderID, lngOrdersDetailsID, lngCustomerID, strOrderType, strCurrency, envMode, strSKU, null);
        }
        
        /// <remarks/>
        public void ValidateOrderDetailsAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, int lngOMSOrderID, int lngOrdersDetailsID, int lngCustomerID, string strOrderType, string strCurrency, string envMode, string strSKU, object userState) {
            if ((this.ValidateOrderDetailsOperationCompleted == null)) {
                this.ValidateOrderDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateOrderDetailsOperationCompleted);
            }
            this.InvokeAsync("ValidateOrderDetails", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        lngOMSOrderID,
                        lngOrdersDetailsID,
                        lngCustomerID,
                        strOrderType,
                        strCurrency,
                        envMode,
                        strSKU}, this.ValidateOrderDetailsOperationCompleted, userState);
        }
        
        private void OnValidateOrderDetailsOperationCompleted(object arg) {
            if ((this.ValidateOrderDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateOrderDetailsCompleted(this, new ValidateOrderDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx/SendOrderConfirmation" +
            "", RequestNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", ResponseNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOrderConfirmation(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, int lngOMSOrderID, string strType, string bLiveMode) {
            object[] results = this.Invoke("SendOrderConfirmation", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        lngOMSOrderID,
                        strType,
                        bLiveMode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOrderConfirmationAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, int lngOMSOrderID, string strType, string bLiveMode) {
            this.SendOrderConfirmationAsync(strB2BCustomerName, strB2BCustomerEmail, strB2BCustomerPassword, lngOMSOrderID, strType, bLiveMode, null);
        }
        
        /// <remarks/>
        public void SendOrderConfirmationAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, int lngOMSOrderID, string strType, string bLiveMode, object userState) {
            if ((this.SendOrderConfirmationOperationCompleted == null)) {
                this.SendOrderConfirmationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrderConfirmationOperationCompleted);
            }
            this.InvokeAsync("SendOrderConfirmation", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        lngOMSOrderID,
                        strType,
                        bLiveMode}, this.SendOrderConfirmationOperationCompleted, userState);
        }
        
        private void OnSendOrderConfirmationOperationCompleted(object arg) {
            if ((this.SendOrderConfirmationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrderConfirmationCompleted(this, new SendOrderConfirmationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx/ViewOrderDetails", RequestNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", ResponseNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ViewOrderDetails(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string strTransactionType, int lngOrderID, string strMerchantOrderNumber, string strOrderStatus, string dtmOrdersFromDate, bool bReturnXML) {
            object[] results = this.Invoke("ViewOrderDetails", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        strTransactionType,
                        lngOrderID,
                        strMerchantOrderNumber,
                        strOrderStatus,
                        dtmOrdersFromDate,
                        bReturnXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ViewOrderDetailsAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string strTransactionType, int lngOrderID, string strMerchantOrderNumber, string strOrderStatus, string dtmOrdersFromDate, bool bReturnXML) {
            this.ViewOrderDetailsAsync(strB2BCustomerName, strB2BCustomerEmail, strB2BCustomerPassword, strTransactionType, lngOrderID, strMerchantOrderNumber, strOrderStatus, dtmOrdersFromDate, bReturnXML, null);
        }
        
        /// <remarks/>
        public void ViewOrderDetailsAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string strTransactionType, int lngOrderID, string strMerchantOrderNumber, string strOrderStatus, string dtmOrdersFromDate, bool bReturnXML, object userState) {
            if ((this.ViewOrderDetailsOperationCompleted == null)) {
                this.ViewOrderDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewOrderDetailsOperationCompleted);
            }
            this.InvokeAsync("ViewOrderDetails", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        strTransactionType,
                        lngOrderID,
                        strMerchantOrderNumber,
                        strOrderStatus,
                        dtmOrdersFromDate,
                        bReturnXML}, this.ViewOrderDetailsOperationCompleted, userState);
        }
        
        private void OnViewOrderDetailsOperationCompleted(object arg) {
            if ((this.ViewOrderDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewOrderDetailsCompleted(this, new ViewOrderDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx/SendEmailViaWS", RequestNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", ResponseNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendEmailViaWS(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string strFrom, string strTo, string strCC, string strBCC, string strSubject, string strBody, bool bHTML) {
            object[] results = this.Invoke("SendEmailViaWS", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        strFrom,
                        strTo,
                        strCC,
                        strBCC,
                        strSubject,
                        strBody,
                        bHTML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailViaWSAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string strFrom, string strTo, string strCC, string strBCC, string strSubject, string strBody, bool bHTML) {
            this.SendEmailViaWSAsync(strB2BCustomerName, strB2BCustomerEmail, strB2BCustomerPassword, strFrom, strTo, strCC, strBCC, strSubject, strBody, bHTML, null);
        }
        
        /// <remarks/>
        public void SendEmailViaWSAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string strFrom, string strTo, string strCC, string strBCC, string strSubject, string strBody, bool bHTML, object userState) {
            if ((this.SendEmailViaWSOperationCompleted == null)) {
                this.SendEmailViaWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailViaWSOperationCompleted);
            }
            this.InvokeAsync("SendEmailViaWS", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        strFrom,
                        strTo,
                        strCC,
                        strBCC,
                        strSubject,
                        strBody,
                        bHTML}, this.SendEmailViaWSOperationCompleted, userState);
        }
        
        private void OnSendEmailViaWSOperationCompleted(object arg) {
            if ((this.SendEmailViaWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailViaWSCompleted(this, new SendEmailViaWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx/ExportOrders", RequestNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", ResponseNamespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExportOrders(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string dtmOrdersFromDate, string strTimeZone, string strTransactionType, string strOrderID, string strMerchantOrderID, string strOrderStatus) {
            object[] results = this.Invoke("ExportOrders", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        dtmOrdersFromDate,
                        strTimeZone,
                        strTransactionType,
                        strOrderID,
                        strMerchantOrderID,
                        strOrderStatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExportOrdersAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string dtmOrdersFromDate, string strTimeZone, string strTransactionType, string strOrderID, string strMerchantOrderID, string strOrderStatus) {
            this.ExportOrdersAsync(strB2BCustomerName, strB2BCustomerEmail, strB2BCustomerPassword, dtmOrdersFromDate, strTimeZone, strTransactionType, strOrderID, strMerchantOrderID, strOrderStatus, null);
        }
        
        /// <remarks/>
        public void ExportOrdersAsync(string strB2BCustomerName, string strB2BCustomerEmail, string strB2BCustomerPassword, string dtmOrdersFromDate, string strTimeZone, string strTransactionType, string strOrderID, string strMerchantOrderID, string strOrderStatus, object userState) {
            if ((this.ExportOrdersOperationCompleted == null)) {
                this.ExportOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportOrdersOperationCompleted);
            }
            this.InvokeAsync("ExportOrders", new object[] {
                        strB2BCustomerName,
                        strB2BCustomerEmail,
                        strB2BCustomerPassword,
                        dtmOrdersFromDate,
                        strTimeZone,
                        strTransactionType,
                        strOrderID,
                        strMerchantOrderID,
                        strOrderStatus}, this.ExportOrdersOperationCompleted, userState);
        }
        
        private void OnExportOrdersOperationCompleted(object arg) {
            if ((this.ExportOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportOrdersCompleted(this, new ExportOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx")]
    public partial class PurchaseOrder {
        
        private string b2BCustomerEmailField;
        
        private string b2BCustomerPasswordField;
        
        private string b2BCustomerNameField;
        
        private string emailAddressField;
        
        private string externalIDField;
        
        private int refIDField;
        
        private string vendorCompanyField;
        
        private string vendorFNameField;
        
        private string vendorLNameField;
        
        private string vendorAddress_1Field;
        
        private string vendorAddress_2Field;
        
        private string vendorCityField;
        
        private string vendorStateField;
        
        private string vendorZipField;
        
        private string vendorCountryField;
        
        private string vendorPhoneField;
        
        private bool shipToSameAsVendorField;
        
        private string shipToCompanyField;
        
        private string shipToFNameField;
        
        private string shipToLNameField;
        
        private string shipToAddress1Field;
        
        private string shipToAddress2Field;
        
        private string shipToCityField;
        
        private string shipToStateField;
        
        private string shipToZipField;
        
        private string shipToCountryField;
        
        private string shipToPhoneField;
        
        private string merchantPONumberField;
        
        private string merchantOrderNumberField;
        
        private string commentsField;
        
        private float handlingField;
        
        private float flatRateShippingField;
        
        private float taxField;
        
        private float shipFeeField;
        
        private string shipMethodField;
        
        private string shipAccountField;
        
        private string pOTermField;
        
        private OrderLineItem[] orderLineItemsField;
        
        private string priorityField;
        
        private string loginClientUserRoleIDField;
        
        private bool bLiveModeField;
        
        private string currencyField;
        
        private bool emailVendorField;
        
        /// <remarks/>
        public string B2BCustomerEmail {
            get {
                return this.b2BCustomerEmailField;
            }
            set {
                this.b2BCustomerEmailField = value;
            }
        }
        
        /// <remarks/>
        public string B2BCustomerPassword {
            get {
                return this.b2BCustomerPasswordField;
            }
            set {
                this.b2BCustomerPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string B2BCustomerName {
            get {
                return this.b2BCustomerNameField;
            }
            set {
                this.b2BCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalID {
            get {
                return this.externalIDField;
            }
            set {
                this.externalIDField = value;
            }
        }
        
        /// <remarks/>
        public int RefID {
            get {
                return this.refIDField;
            }
            set {
                this.refIDField = value;
            }
        }
        
        /// <remarks/>
        public string VendorCompany {
            get {
                return this.vendorCompanyField;
            }
            set {
                this.vendorCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string VendorFName {
            get {
                return this.vendorFNameField;
            }
            set {
                this.vendorFNameField = value;
            }
        }
        
        /// <remarks/>
        public string VendorLName {
            get {
                return this.vendorLNameField;
            }
            set {
                this.vendorLNameField = value;
            }
        }
        
        /// <remarks/>
        public string VendorAddress_1 {
            get {
                return this.vendorAddress_1Field;
            }
            set {
                this.vendorAddress_1Field = value;
            }
        }
        
        /// <remarks/>
        public string VendorAddress_2 {
            get {
                return this.vendorAddress_2Field;
            }
            set {
                this.vendorAddress_2Field = value;
            }
        }
        
        /// <remarks/>
        public string VendorCity {
            get {
                return this.vendorCityField;
            }
            set {
                this.vendorCityField = value;
            }
        }
        
        /// <remarks/>
        public string VendorState {
            get {
                return this.vendorStateField;
            }
            set {
                this.vendorStateField = value;
            }
        }
        
        /// <remarks/>
        public string VendorZip {
            get {
                return this.vendorZipField;
            }
            set {
                this.vendorZipField = value;
            }
        }
        
        /// <remarks/>
        public string VendorCountry {
            get {
                return this.vendorCountryField;
            }
            set {
                this.vendorCountryField = value;
            }
        }
        
        /// <remarks/>
        public string VendorPhone {
            get {
                return this.vendorPhoneField;
            }
            set {
                this.vendorPhoneField = value;
            }
        }
        
        /// <remarks/>
        public bool ShipToSameAsVendor {
            get {
                return this.shipToSameAsVendorField;
            }
            set {
                this.shipToSameAsVendorField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCompany {
            get {
                return this.shipToCompanyField;
            }
            set {
                this.shipToCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToFName {
            get {
                return this.shipToFNameField;
            }
            set {
                this.shipToFNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToLName {
            get {
                return this.shipToLNameField;
            }
            set {
                this.shipToLNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress1 {
            get {
                return this.shipToAddress1Field;
            }
            set {
                this.shipToAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToPhone {
            get {
                return this.shipToPhoneField;
            }
            set {
                this.shipToPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string MerchantPONumber {
            get {
                return this.merchantPONumberField;
            }
            set {
                this.merchantPONumberField = value;
            }
        }
        
        /// <remarks/>
        public string MerchantOrderNumber {
            get {
                return this.merchantOrderNumberField;
            }
            set {
                this.merchantOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public float Handling {
            get {
                return this.handlingField;
            }
            set {
                this.handlingField = value;
            }
        }
        
        /// <remarks/>
        public float FlatRateShipping {
            get {
                return this.flatRateShippingField;
            }
            set {
                this.flatRateShippingField = value;
            }
        }
        
        /// <remarks/>
        public float Tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public float ShipFee {
            get {
                return this.shipFeeField;
            }
            set {
                this.shipFeeField = value;
            }
        }
        
        /// <remarks/>
        public string ShipMethod {
            get {
                return this.shipMethodField;
            }
            set {
                this.shipMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ShipAccount {
            get {
                return this.shipAccountField;
            }
            set {
                this.shipAccountField = value;
            }
        }
        
        /// <remarks/>
        public string POTerm {
            get {
                return this.pOTermField;
            }
            set {
                this.pOTermField = value;
            }
        }
        
        /// <remarks/>
        public OrderLineItem[] OrderLineItems {
            get {
                return this.orderLineItemsField;
            }
            set {
                this.orderLineItemsField = value;
            }
        }
        
        /// <remarks/>
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public string LoginClientUserRoleID {
            get {
                return this.loginClientUserRoleIDField;
            }
            set {
                this.loginClientUserRoleIDField = value;
            }
        }
        
        /// <remarks/>
        public bool bLiveMode {
            get {
                return this.bLiveModeField;
            }
            set {
                this.bLiveModeField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public bool EmailVendor {
            get {
                return this.emailVendorField;
            }
            set {
                this.emailVendorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx")]
    public partial class OrderLineItem {
        
        private int lineNumberField;
        
        private float quantityOrderedField;
        
        private string sKUField;
        
        private string sKUWMSField;
        
        private float unitPriceField;
        
        private float unitPriceDiscountField;
        
        private string itemNameField;
        
        private string orderLineItem3PLIDField;
        
        private string itemBarCodeField;
        
        private string warehouseNameField;
        
        /// <remarks/>
        public int LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        public float QuantityOrdered {
            get {
                return this.quantityOrderedField;
            }
            set {
                this.quantityOrderedField = value;
            }
        }
        
        /// <remarks/>
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        public string SKUWMS {
            get {
                return this.sKUWMSField;
            }
            set {
                this.sKUWMSField = value;
            }
        }
        
        /// <remarks/>
        public float UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public float UnitPriceDiscount {
            get {
                return this.unitPriceDiscountField;
            }
            set {
                this.unitPriceDiscountField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string OrderLineItem3PLID {
            get {
                return this.orderLineItem3PLIDField;
            }
            set {
                this.orderLineItem3PLIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemBarCode {
            get {
                return this.itemBarCodeField;
            }
            set {
                this.itemBarCodeField = value;
            }
        }
        
        /// <remarks/>
        public string WarehouseName {
            get {
                return this.warehouseNameField;
            }
            set {
                this.warehouseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx")]
    public partial class OrderComment {
        
        private string commentField;
        
        private string commentTypeField;
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string CommentType {
            get {
                return this.commentTypeField;
            }
            set {
                this.commentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx")]
    public partial class OrderPayment {
        
        private string externalIDField;
        
        private float paymentAmountField;
        
        private System.DateTime postPaymentDateField;
        
        /// <remarks/>
        public string ExternalID {
            get {
                return this.externalIDField;
            }
            set {
                this.externalIDField = value;
            }
        }
        
        /// <remarks/>
        public float PaymentAmount {
            get {
                return this.paymentAmountField;
            }
            set {
                this.paymentAmountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PostPaymentDate {
            get {
                return this.postPaymentDateField;
            }
            set {
                this.postPaymentDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx")]
    public partial class SalesOrder {
        
        private string transCodeField;
        
        private string authCodeField;
        
        private OrderStatus statusField;
        
        private string emailAddressField;
        
        private string externalIDField;
        
        private string clientRoleNameField;
        
        private string billToCompanyField;
        
        private string billToFNameField;
        
        private string billToLNameField;
        
        private string billToAddress1Field;
        
        private string billToAddress2Field;
        
        private string billToCityField;
        
        private string billToStateField;
        
        private string billToZipField;
        
        private string billToCountryField;
        
        private string billToPhoneField;
        
        private bool shipToSameAsBillToField;
        
        private string shipToCompanyField;
        
        private string shipToFNameField;
        
        private string shipToLNameField;
        
        private string shipToAddress1Field;
        
        private string shipToAddress2Field;
        
        private string shipToCityField;
        
        private string shipToStateField;
        
        private string shipToZipField;
        
        private string shipToCountryField;
        
        private string shipToPhoneField;
        
        private string shipToEmailAddressField;
        
        private string merchantPONumberField;
        
        private string merchantOrderNumberField;
        
        private string commentsField;
        
        private string billToShipTo3PLIDField;
        
        private float pricingDiscountField;
        
        private float couponDiscountField;
        
        private float handlingField;
        
        private float flatRateShippingField;
        
        private float taxField;
        
        private float shipFeeField;
        
        private string shipMethodField;
        
        private string shipAccountField;
        
        private string pOTermField;
        
        private OrderLineItem[] orderLineItemsField;
        
        private string priorityField;
        
        private int refIDField;
        
        private string b2BCustomerEmailField;
        
        private string b2BCustomerPasswordField;
        
        private string b2BCustomerNameField;
        
        private string referrerNameField;
        
        private string paymentTypeField;
        
        private string nameOnCardField;
        
        private string creditCardNumberField;
        
        private int creditCardExpMonField;
        
        private int creditCardExpYrField;
        
        private bool optInField;
        
        private bool emailCustomerField;
        
        private OrderPayment[] orderPaymentsField;
        
        private System.DateTime orderDateField;
        
        private System.DateTime requestedShipDateField;
        
        private System.DateTime requestedDeliveryDateField;
        
        private OrderComment[] orderCommentsField;
        
        private bool billToResidentialField;
        
        private bool shipToResidentialField;
        
        private string currencyField;
        
        private string languageField;
        
        private bool checkForDuplicatesField;
        
        private int hoursForDuplicateCheckField;
        
        private string eDI_TransactionTypeField;
        
        private bool eDI_EmailClientField;
        
        private string eDI_FileNameField;
        
        private System.DateTime eDI_NotBeforeField;
        
        private System.DateTime eDI_CancelAfterField;
        
        private string eDI_Description1Field;
        
        private string eDI_Description2Field;
        
        private string eDI_Description3Field;
        
        private string eDI_Description4Field;
        
        private string eDI_Description5Field;
        
        private string shipReference_1Field;
        
        private string shipReference_2Field;
        
        private string shipMethod3PLIDField;
        
        private bool checkOverrideLineItemTotalField;
        
        private float overrideLineItemTotalAmountField;
        
        private bool validateOnlyMOrderIDField;
        
        /// <remarks/>
        public string TransCode {
            get {
                return this.transCodeField;
            }
            set {
                this.transCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        public OrderStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalID {
            get {
                return this.externalIDField;
            }
            set {
                this.externalIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClientRoleName {
            get {
                return this.clientRoleNameField;
            }
            set {
                this.clientRoleNameField = value;
            }
        }
        
        /// <remarks/>
        public string BillToCompany {
            get {
                return this.billToCompanyField;
            }
            set {
                this.billToCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string BillToFName {
            get {
                return this.billToFNameField;
            }
            set {
                this.billToFNameField = value;
            }
        }
        
        /// <remarks/>
        public string BillToLName {
            get {
                return this.billToLNameField;
            }
            set {
                this.billToLNameField = value;
            }
        }
        
        /// <remarks/>
        public string BillToAddress1 {
            get {
                return this.billToAddress1Field;
            }
            set {
                this.billToAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string BillToAddress2 {
            get {
                return this.billToAddress2Field;
            }
            set {
                this.billToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string BillToCity {
            get {
                return this.billToCityField;
            }
            set {
                this.billToCityField = value;
            }
        }
        
        /// <remarks/>
        public string BillToState {
            get {
                return this.billToStateField;
            }
            set {
                this.billToStateField = value;
            }
        }
        
        /// <remarks/>
        public string BillToZip {
            get {
                return this.billToZipField;
            }
            set {
                this.billToZipField = value;
            }
        }
        
        /// <remarks/>
        public string BillToCountry {
            get {
                return this.billToCountryField;
            }
            set {
                this.billToCountryField = value;
            }
        }
        
        /// <remarks/>
        public string BillToPhone {
            get {
                return this.billToPhoneField;
            }
            set {
                this.billToPhoneField = value;
            }
        }
        
        /// <remarks/>
        public bool ShipToSameAsBillTo {
            get {
                return this.shipToSameAsBillToField;
            }
            set {
                this.shipToSameAsBillToField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCompany {
            get {
                return this.shipToCompanyField;
            }
            set {
                this.shipToCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToFName {
            get {
                return this.shipToFNameField;
            }
            set {
                this.shipToFNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToLName {
            get {
                return this.shipToLNameField;
            }
            set {
                this.shipToLNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress1 {
            get {
                return this.shipToAddress1Field;
            }
            set {
                this.shipToAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToAddress2 {
            get {
                return this.shipToAddress2Field;
            }
            set {
                this.shipToAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCity {
            get {
                return this.shipToCityField;
            }
            set {
                this.shipToCityField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToState {
            get {
                return this.shipToStateField;
            }
            set {
                this.shipToStateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToZip {
            get {
                return this.shipToZipField;
            }
            set {
                this.shipToZipField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToPhone {
            get {
                return this.shipToPhoneField;
            }
            set {
                this.shipToPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string ShipToEmailAddress {
            get {
                return this.shipToEmailAddressField;
            }
            set {
                this.shipToEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string MerchantPONumber {
            get {
                return this.merchantPONumberField;
            }
            set {
                this.merchantPONumberField = value;
            }
        }
        
        /// <remarks/>
        public string MerchantOrderNumber {
            get {
                return this.merchantOrderNumberField;
            }
            set {
                this.merchantOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string BillToShipTo3PLID {
            get {
                return this.billToShipTo3PLIDField;
            }
            set {
                this.billToShipTo3PLIDField = value;
            }
        }
        
        /// <remarks/>
        public float PricingDiscount {
            get {
                return this.pricingDiscountField;
            }
            set {
                this.pricingDiscountField = value;
            }
        }
        
        /// <remarks/>
        public float CouponDiscount {
            get {
                return this.couponDiscountField;
            }
            set {
                this.couponDiscountField = value;
            }
        }
        
        /// <remarks/>
        public float Handling {
            get {
                return this.handlingField;
            }
            set {
                this.handlingField = value;
            }
        }
        
        /// <remarks/>
        public float FlatRateShipping {
            get {
                return this.flatRateShippingField;
            }
            set {
                this.flatRateShippingField = value;
            }
        }
        
        /// <remarks/>
        public float Tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public float ShipFee {
            get {
                return this.shipFeeField;
            }
            set {
                this.shipFeeField = value;
            }
        }
        
        /// <remarks/>
        public string ShipMethod {
            get {
                return this.shipMethodField;
            }
            set {
                this.shipMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ShipAccount {
            get {
                return this.shipAccountField;
            }
            set {
                this.shipAccountField = value;
            }
        }
        
        /// <remarks/>
        public string POTerm {
            get {
                return this.pOTermField;
            }
            set {
                this.pOTermField = value;
            }
        }
        
        /// <remarks/>
        public OrderLineItem[] OrderLineItems {
            get {
                return this.orderLineItemsField;
            }
            set {
                this.orderLineItemsField = value;
            }
        }
        
        /// <remarks/>
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public int RefID {
            get {
                return this.refIDField;
            }
            set {
                this.refIDField = value;
            }
        }
        
        /// <remarks/>
        public string B2BCustomerEmail {
            get {
                return this.b2BCustomerEmailField;
            }
            set {
                this.b2BCustomerEmailField = value;
            }
        }
        
        /// <remarks/>
        public string B2BCustomerPassword {
            get {
                return this.b2BCustomerPasswordField;
            }
            set {
                this.b2BCustomerPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string B2BCustomerName {
            get {
                return this.b2BCustomerNameField;
            }
            set {
                this.b2BCustomerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReferrerName {
            get {
                return this.referrerNameField;
            }
            set {
                this.referrerNameField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string NameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardNumber {
            get {
                return this.creditCardNumberField;
            }
            set {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public int CreditCardExpMon {
            get {
                return this.creditCardExpMonField;
            }
            set {
                this.creditCardExpMonField = value;
            }
        }
        
        /// <remarks/>
        public int CreditCardExpYr {
            get {
                return this.creditCardExpYrField;
            }
            set {
                this.creditCardExpYrField = value;
            }
        }
        
        /// <remarks/>
        public bool OptIn {
            get {
                return this.optInField;
            }
            set {
                this.optInField = value;
            }
        }
        
        /// <remarks/>
        public bool EmailCustomer {
            get {
                return this.emailCustomerField;
            }
            set {
                this.emailCustomerField = value;
            }
        }
        
        /// <remarks/>
        public OrderPayment[] OrderPayments {
            get {
                return this.orderPaymentsField;
            }
            set {
                this.orderPaymentsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestedShipDate {
            get {
                return this.requestedShipDateField;
            }
            set {
                this.requestedShipDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestedDeliveryDate {
            get {
                return this.requestedDeliveryDateField;
            }
            set {
                this.requestedDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        public OrderComment[] OrderComments {
            get {
                return this.orderCommentsField;
            }
            set {
                this.orderCommentsField = value;
            }
        }
        
        /// <remarks/>
        public bool BillToResidential {
            get {
                return this.billToResidentialField;
            }
            set {
                this.billToResidentialField = value;
            }
        }
        
        /// <remarks/>
        public bool ShipToResidential {
            get {
                return this.shipToResidentialField;
            }
            set {
                this.shipToResidentialField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public bool CheckForDuplicates {
            get {
                return this.checkForDuplicatesField;
            }
            set {
                this.checkForDuplicatesField = value;
            }
        }
        
        /// <remarks/>
        public int HoursForDuplicateCheck {
            get {
                return this.hoursForDuplicateCheckField;
            }
            set {
                this.hoursForDuplicateCheckField = value;
            }
        }
        
        /// <remarks/>
        public string EDI_TransactionType {
            get {
                return this.eDI_TransactionTypeField;
            }
            set {
                this.eDI_TransactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool EDI_EmailClient {
            get {
                return this.eDI_EmailClientField;
            }
            set {
                this.eDI_EmailClientField = value;
            }
        }
        
        /// <remarks/>
        public string EDI_FileName {
            get {
                return this.eDI_FileNameField;
            }
            set {
                this.eDI_FileNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EDI_NotBefore {
            get {
                return this.eDI_NotBeforeField;
            }
            set {
                this.eDI_NotBeforeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EDI_CancelAfter {
            get {
                return this.eDI_CancelAfterField;
            }
            set {
                this.eDI_CancelAfterField = value;
            }
        }
        
        /// <remarks/>
        public string EDI_Description1 {
            get {
                return this.eDI_Description1Field;
            }
            set {
                this.eDI_Description1Field = value;
            }
        }
        
        /// <remarks/>
        public string EDI_Description2 {
            get {
                return this.eDI_Description2Field;
            }
            set {
                this.eDI_Description2Field = value;
            }
        }
        
        /// <remarks/>
        public string EDI_Description3 {
            get {
                return this.eDI_Description3Field;
            }
            set {
                this.eDI_Description3Field = value;
            }
        }
        
        /// <remarks/>
        public string EDI_Description4 {
            get {
                return this.eDI_Description4Field;
            }
            set {
                this.eDI_Description4Field = value;
            }
        }
        
        /// <remarks/>
        public string EDI_Description5 {
            get {
                return this.eDI_Description5Field;
            }
            set {
                this.eDI_Description5Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipReference_1 {
            get {
                return this.shipReference_1Field;
            }
            set {
                this.shipReference_1Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipReference_2 {
            get {
                return this.shipReference_2Field;
            }
            set {
                this.shipReference_2Field = value;
            }
        }
        
        /// <remarks/>
        public string ShipMethod3PLID {
            get {
                return this.shipMethod3PLIDField;
            }
            set {
                this.shipMethod3PLIDField = value;
            }
        }
        
        /// <remarks/>
        public bool CheckOverrideLineItemTotal {
            get {
                return this.checkOverrideLineItemTotalField;
            }
            set {
                this.checkOverrideLineItemTotalField = value;
            }
        }
        
        /// <remarks/>
        public float OverrideLineItemTotalAmount {
            get {
                return this.overrideLineItemTotalAmountField;
            }
            set {
                this.overrideLineItemTotalAmountField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidateOnlyMOrderID {
            get {
                return this.validateOnlyMOrderIDField;
            }
            set {
                this.validateOnlyMOrderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.shoptvcanada.com/omsordertaker/omsordertaker.asmx")]
    public enum OrderStatus {
        
        /// <remarks/>
        PendingPOQuote,
        
        /// <remarks/>
        Processing,
        
        /// <remarks/>
        Void,
        
        /// <remarks/>
        Decline,
        
        /// <remarks/>
        PendingApproval,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        PendingMailPayment,
        
        /// <remarks/>
        OnHold,
        
        /// <remarks/>
        Complete,
        
        /// <remarks/>
        SuspectedFraud,
        
        /// <remarks/>
        PendingReviewPayment,
        
        /// <remarks/>
        PendingNetPayment,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConnectionTestCompletedEventHandler(object sender, ConnectionTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConnectionTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConnectionTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreatePurchaseOrderCompletedEventHandler(object sender, CreatePurchaseOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePurchaseOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePurchaseOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateSalesOrderCompletedEventHandler(object sender, CreateSalesOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSalesOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSalesOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidateOrderDetailsCompletedEventHandler(object sender, ValidateOrderDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateOrderDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateOrderDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strSKU {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendOrderConfirmationCompletedEventHandler(object sender, SendOrderConfirmationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrderConfirmationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOrderConfirmationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ViewOrderDetailsCompletedEventHandler(object sender, ViewOrderDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewOrderDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViewOrderDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendEmailViaWSCompletedEventHandler(object sender, SendEmailViaWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailViaWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailViaWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ExportOrdersCompletedEventHandler(object sender, ExportOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591